env:
  BUILDKITE_PLUGIN_FS_CACHE_FOLDER: "/opt/homebrew/var/cache/buildkite"
steps:
  - label: ':nodejs: Install dependencies'
    command: mkdir node_modules; echo "$(date +%Y%m%d_%H%M%S)" > yarn.lock; npm ci
    plugins:
      - cache#v1.4.0:
          manifest: yarn.lock
          path: "tmp/yarn/cache"
          save:
            - pipeline
  - label: ':nodejs: Run tests'
    command: echo "Running tests" && sleep 10
    plugins:
      - cache#v1.4.0:
          manifest: yarn.lock
          path: "node_modules"
          restore: pipeline
