steps:
  - label: "Generate Logs and Fail Twice"
    command: |
      echo "Build attempt number \$BUILDKITE_RETRY_COUNT" > build.log
      if [ "\$BUILDKITE_RETRY_COUNT" != "5" ]; then
        echo "This run will fail intentionally." >> build.log
        exit 1
      else
        echo "This run will succeed." >> build.log
      fi
    artifact_paths: "build.log"
    continue_on_failure: true
    retry:
      automatic:
        - exit_status: 1 # Retry on failure with exit status 1
          limit: 4       # Retry up to 3 times

  - wait: ~

  - label: "Download Artifact"
    continue_on_failure: true
    command: |
      buildkite-agent artifact download "build.log" .
      cat build.log
