steps:
  - label: "Annotate Git Diff"
    command: |
      git diff HEAD~1..HEAD > tempdiff.txt
      buildkite-agent annotate --job 0196f094-8464-4d8b-831b-975faf18651e --style "default" --context "diff" "<pre>$(cat tempdiff.txt)</pre>"
