steps:
  - key: "np-check-formatting"
    label: "NP | Check go formatting"
    commands: "cd /workdir; ls -la"
    plugins:
      - docker#v5.9.0:
          image: "golang:1.22.1"
          shell:
            - "/bin/bash"
            - "-c"
          network: "host"
          environment:
            - "GO_BIN_PATH=/go/bin"
          propagate-uid-gid: true
          workdir: "/app"
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
