env:
  AWS_ECR: "097340723131.dkr.ecr.ap-southeast-2.amazonaws.com/"
steps:
  - label: ":docker: :package:"
    agents:
      queue: "default"
    command: ""
    plugins:
    - github.com/buildkite-plugins/docker-compose-buildkite-plugin#v5.6.0:
        push:
        - "app:${AWS_ECR}/build-cache/jykingston/nurtien:latest"
        build: "app"
        config: "docker-compose.yml"
        builder:
          use: true
          name: "container"
          create: true
          driver: "docker-container"
        cache-to:
        - "app:type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=097340723131.dkr.ecr.ap-southeast-2.amazonaws.com/build-cache/jykingston/nutrien:cache"
        cache-from:
        - "app:type=registry,ref=097340723131.dkr.ecr.ap-southeast-2.amazonaws.com/build-cache/jykingston/nutrien:cache"
