env:
  AWS_ECR: "097340723131.dkr.ecr.ap-southeast-2.amazonaws.com/"
steps:
  - label: "Install and Configure Docker ECR Helper"
    command: |
      sudo su;
      curl -Lo /usr/local/bin/docker-credential-ecr-login https://github.com/awslabs/amazon-ecr-credential-helper/releases/latest/download/docker-credential-ecr-login
      chmod +x /usr/local/bin/docker-credential-ecr-login
      mkdir -p ~/.docker
      echo '{"credsStore": "ecr-login","credHelpers":{"097340723131.dkr.ecr.ap-southeast-2.amazonaws.com":"ecr-login"}}' > ~/.docker/config.json
  - label: ":docker: :package:"
    agents:
      queue: "default"
    command: ""
    plugins:
    - github.com/buildkite-plugins/docker-compose-buildkite-plugin#v5.6.0:
        push:
        - "app:${AWS_ECR}/build-cache/jykingston/nurtien:latest"
        build: "app"
        config: "docker-compose.yml"
        builder:
          use: true
          name: "container"
          create: true
          driver: "docker-container"
        cache-to:
        - "app:type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=097340723131.dkr.ecr.ap-southeast-2.amazonaws.com/build-cache/jykingston/nutrien:cache"
        cache-from:
        - "app:type=registry,ref=097340723131.dkr.ecr.ap-southeast-2.amazonaws.com/build-cache/jykingston/nutrien:cache"
