env:
  BUILDKITE_PLUGIN_S3_CACHE_BUCKET: "jykingston-buildkite-test-storage"
steps:
  - label: ':nodejs: Install dependencies'
    command: mkdir node_modules; echo "$(date +%Y%m%d_%H%M%S)" > yarn.lock; npm ci
    plugins:
 #     - cache#v1.5.2:
 #         manifest: "yarn.lock"
 #         path: "node_modules"
 #         save: "pipeline"
 #         compression: "tgz"
 #         backend: "s3"
    - github.com/buildkite-plugins/cache-buildkite-plugin#v1.5.2:
        path: "node_modules"
        save: "pipeline"
        backend: "s3"
        manifest: "yarn.lock"
        compression: "tgz"
  - label: ':nodejs: Run tests'
    command: echo "Running tests" && sleep 10
    plugins:
  #    - cache#v1.5.2:
  #        manifest: "yarn.lock"
  #        path: "node_modules"
  #        restore: "pipeline"
  #        compression: "tgz"
  #        backend: "s3"
    - github.com/buildkite-plugins/cache-buildkite-plugin#v1.5.2:
        path: "node_modules"
        backend: "s3"
        restore: "pipeline"
        manifest: "yarn.lock"
        compression: "tgz"
