steps:
  - label: "Generate Logs and Fail Twice"
    command: |
      echo "Build attempt number \$BUILDKITE_BUILD_NUMBER" > build.log
      if [ "\$BUILDKITE_BUILD_NUMBER" == "1" ] || [ "\$BUILDKITE_BUILD_NUMBER" == "2" ]; then
        echo "This run will fail intentionally." >> build.log
        exit 1
      else
        echo "This run will succeed." >> build.log
      fi
    artifact_paths: "build.log"
    retry:
      automatic:
        - exit_status: 1 # Retry on failure with exit status 1
          limit: 3       # Retry up to 3 times

  - wait

  - label: "Download Artifact"
    command: |
      buildkite-agent artifact download "build.log" .
      cat build.log
    depends_on: 
      - "*"
