#!/bin/bash

# Variables
S3_BUCKET="jykingston-buildkite-test-storage"
SINGING_KEYS_S3_PATH="singing-keys"
SSH_KEYS_S3_PATH="ssh-keys"
LOCAL_DESTINATION="/tmp/"
CONFIG_FILE="/etc/buildkite-agent/buildkite-agent.cfg"
KEY_ID="distinct-warthog"

# Function to pull Singing Key files from S3
pull_files_from_s3() {
    echo "Pulling files from S3 bucket: $S3_BUCKET"
    aws s3 sync s3://$S3_BUCKET/$SINGING_KEYS_S3_PATH $LOCAL_DESTINATION
    aws s3 sync s3://$S3_BUCKET/$SSH_KEYS_S3_PATH $LOCAL_DESTINATION
}

# Function to append file locations to the config file
append_to_config() {
    echo "Appending singing config to $CONFIG_FILE"
    echo "signing-jwks-file=/tmp/private.json" >>$CONFIG_FILE
    echo "signing-jwks-key-id=${KEY_ID}" >>$CONFIG_FILE
    echo "verification-jwks-file=/tmp/public.json" >>$CONFIG_FILE
}

# Function to add the SSH keys to the correct locations on the agent for Github access
add_ssh_keys() {
    echo "Adding SSH keys to the agent"
    mkdir -p /root/.ssh
    cp /tmp/id_rsa /root/.ssh/id_rsa
    cp /tmp/id_rsa.pub /root/.ssh/id_rsa.pub
    chmod 600 /root/.ssh/id_rsa
    chmod 600 /root/.ssh/id_rsa.pub
}

# Main script execution
pull_files_from_s3
append_to_config
add_ssh_keys

echo "Script execution completed."
exit 0
