#!/bin/bash
set -euo pipefail
# This saves really?
echo "Importing the env vars"
#env_vars=$(<"$BUILDKITE_ENV_FILE")
# Declare a bash array for env_vars
#declare -A env_vars
#env_vars=(foo bar)
env_vars=(BUILDKITE_COMMIT="a0dbc05b3cee7e47c2600556c446d0448f168fc2" BUILDKITE_PIPELINE_ID="0191c50b-54ae-4caa-8a07-692ad07e37f9" BUILDKITE_RETRY_COUNT="0" BUILDKITE_ORGANIZATION_ID="0191bacb-3f38-4381-9e1e-0e182de38d43" BUILDKITE_PIPELINE_DEFAULT_BRANCH="main" BUILDKITE_BUILD_PATH="/opt/homebrew/etc/buildkite-agent/working_directory" BUILDKITE_PIPELINE_NAME="Starter pipeline" BUILDKITE_STEP_ID="0193e1ec-87aa-46b1-9015-a7a900d2de53" BUILDKITE_STEP_KEY="" BUILDKITE_JOB_ID="0193e1ec-87ce-4a16-a9d0-a057cf246c45" BUILDKITE="true" BUILDKITE_TRIGGERED_FROM_BUILD_ID="" BUILDKITE_PROJECT_SLUG="jyent-buildkite/starter-pipeline" BUILDKITE_COMMAND="./src/env-vars.sh" BUILDKITE_CLUSTER_ID="6c002213-a8d6-49c3-b458-94059b6eac02" BUILDKITE_AGENT_NAME="Jys-MacBook-Pro-1" BUILDKITE_CLUSTER_NAME="Default cluster" BUILDKITE_PIPELINE_SLUG="starter-pipeline" BUILDKITE_SCRIPT_PATH="./src/env-vars.sh" BUILDKITE_BUILD_NUMBER="283" BUILDKITE_BUILD_ID="0193e1ec-4b4e-4685-8d87-a791f2161faf" BUILDKITE_PIPELINE_PROVIDER="github" BUILDKITE_AGENT_META_DATA_QUEUE="default" BUILDKITE_BUILD_URL="https://buildkite.com/jyent-buildkite/starter-pipeline/builds/283" BUILDKITE_REBUILT_FROM_BUILD_ID="" BUILDKITE_ARTIFACT_PATHS="" BUILDKITE_TIMEOUT="false" BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER="" BUILDKITE_MESSAGE="Try accessing the array entirely.." BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG="" BUILDKITE_PULL_REQUEST_REPO="" BUILDKITE_SOURCE="webhook" CI="true" BUILDKITE_PROJECT_PROVIDER="github" BUILDKITE_PULL_REQUEST="false" BUILDKITE_REBUILT_FROM_BUILD_NUMBER="" BUILDKITE_AGENT_ID="0193e1df-bb62-4f41-b882-6de362968870" BUILDKITE_PULL_REQUEST_BASE_BRANCH="" BUILDKITE_ORGANIZATION_SLUG="jyent-buildkite" BUILDKITE_BUILD_CREATOR_EMAIL="jy@buildkite.com" BUILDKITE_REPO="https://github.com/jykingston/starter.git" BUILDKITE_BUILD_AUTHOR="Jy Kingston" BUILDKITE_COMPUTE_TYPE="self-hosted" BUILDKITE_BUILD_CREATOR="Jy Kingston" BUILDKITE_TAG="" BUILDKITE_BRANCH="main" BUILDKITE_BUILD_AUTHOR_EMAIL="jy@buildkite.com" BUILDKITE_LABEL=":desktop_computer:" BUILDKITE_AGENT_ACCESS_TOKEN="[REDACTED]" BUILDKITE_BUILD_PATH="/opt/homebrew/var/buildkite-agent/builds" BUILDKITE_HOOKS_PATH="/opt/homebrew/etc/buildkite-agent/hooks" BUILDKITE_PLUGINS_PATH="/opt/homebrew/var/buildkite-agent/plugins" BUILDKITE_PLUGIN_VALIDATION="false" BUILDKITE_LOCAL_HOOKS_ENABLED="true" BUILDKITE_SSH_KEYSCAN="true" BUILDKITE_AGENT_DEBUG="false")
echo $env_vars[@]

env_vars+=(
    "BUILDKITE_AGENT_ACCESS_TOKEN"=\"${BUILDKITE_AGENT_ACCESS_TOKEN_SUBAGENT:-$BUILDKITE_AGENT_ACCESS_TOKEN}\"
    "BUILDKITE_BUILD_PATH"=\"${BUILDKITE_BUILD_PATH_SUBAGENT:-$BUILDKITE_BUILD_PATH}\"
    "BUILDKITE_HOOKS_PATH"=\"${BUILDKITE_HOOKS_PATH_SUBAGENT:-$BUILDKITE_HOOKS_PATH}\"
    "BUILDKITE_PLUGINS_PATH"=\"${BUILDKITE_PLUGINS_PATH_SUBAGENT:-$BUILDKITE_PLUGINS_PATH}\"
    "BUILDKITE_PLUGIN_VALIDATION"=\"${BUILDKITE_PLUGIN_VALIDATION_SUBAGENT:-$BUILDKITE_PLUGIN_VALIDATION}\"
    "BUILDKITE_LOCAL_HOOKS_ENABLED"=\"${BUILDKITE_LOCAL_HOOKS_ENABLED_SUBAGENT:-$BUILDKITE_LOCAL_HOOKS_ENABLED}\"
    "BUILDKITE_SSH_KEYSCAN"=\"${BUILDKITE_SSH_KEYSCAN_SUBAGENT:-$BUILDKITE_SSH_KEYSCAN}\"
    "BUILDKITE_AGENT_DEBUG"=\"${BUILDKITE_AGENT_DEBUG_SUBAGENT:-$BUILDKITE_AGENT_DEBUG}\"
)

echo "Print the env_vars array with all elements"
echo ${env_vars[@]}
echo "--------------------------------------------"
echo "Print it with zsh array"
zsh -c "echo $env_vars[@]"

echo "Print it with zsh array []"
zsh -c "echo $env_vars[]"


echo "Print it with zsh array [*]"
zsh -c "echo $env_vars[*]"


