#!/bin/bash

buildkite-agent --version
echo "BUILDKITE_REDACTED_VARS=\"$BUILDKITE_REDACTED_VARS\""

SECRET_TOKEN_1="secret-token-1"
echo "SECRET_TOKEN_1: $SECRET_TOKEN_1"

SECRET_TOKEN_2="secret-token-2"

set -x
echo "SECRET_TOKEN_1: $SECRET_TOKEN_1"
echo "SECRET_TOKEN_2: $SECRET_TOKEN_2"

export BUILDKITE_REDACTED_VARS="$BUILDKITE_REDACTED_VARS,SECRET_TOKEN_1,SECRET_TOKEN_2"
echo "SECRET_TOKEN_1: $SECRET_TOKEN_1"

export BUILDKITE_REDACTED_VARS="$BUILDKITE_REDACTED_VARS SECRET_TOKEN_1 SECRET_TOKEN_2"
echo "SECRET_TOKEN_2: $SECRET_TOKEN_2"
